# Generated by Django 5.1.1 on 2024-09-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_register_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
